#!/usr/bin/env ruby
$: << File.expand_path("#{File.dirname __FILE__}/../lib")
#!/usr/bin/env ruby
#$: << File.expand_path("#{File.dirname __FILE__}/../lib")
require 'mysql/partitioner'

Mysql::Partitioner::Cli.new.run()

